name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd server/
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd ..
        cd client/
        yarn install
    - name: Build Client UI
      run: |
        cd client/
        yarn serve
    - name: Run Tests
      run: |
        cd server/
        python manage.py test